<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.070" timestamp="2025-09-22T03:19:45.654066+02:00" hostname="MacBook-Air.local"><testcase classname="" name="tests.test_main" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/artem/Documents/Programming/Python/translate_API/API_translate/translate-api/tests/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test_main.py:4: in &lt;module&gt;
    from app.main import get_translation, translation_samples, ids
../app/main.py:2: in &lt;module&gt;
    from config import BASE_URL
E   ModuleNotFoundError: No module named 'config'</error></testcase></testsuite></testsuites>